/**
 * Generated by react-api-weaver
 * User Management API - 1.0.0
 * REST API for managing user details with CRUD operations
 * Do not edit manually
 */

import { makeRequest } from 'react-api-weaver';
import type { RequestConfig } from 'react-api-weaver';
import type * as ApiTypes from './types';

const BASE_URL = 'http://localhost:3001';

/**
 * Retrieve a list of all users with optional limit parameter
 */
export async function getUsers(params: ApiTypes.GetUsersParams, config?: RequestConfig): Promise<ApiTypes.GetUsersResponse> {
  return makeRequest<ApiTypes.GetUsersResponse>({
    method: 'GET',
    url: `/api/users`,
    params,
    baseURL: BASE_URL,
    ...config,
  });
}

/**
 * Add a new user to the system
 */
export async function createUser(body: ApiTypes.CreateUserBody, config?: RequestConfig): Promise<ApiTypes.CreateUserResponse> {
  return makeRequest<ApiTypes.CreateUserResponse>({
    method: 'POST',
    url: `/api/users`,
    body,
    baseURL: BASE_URL,
    ...config,
  });
}

/**
 * Retrieve a specific user by their ID
 */
export async function getUserById(params: ApiTypes.GetUserByIdParams, config?: RequestConfig): Promise<ApiTypes.GetUserByIdResponse> {
  return makeRequest<ApiTypes.GetUserByIdResponse>({
    method: 'GET',
    url: `/api/users/${params.id}`,
    params,
    baseURL: BASE_URL,
    ...config,
  });
}

/**
 * Replace all user data with new data
 */
export async function updateUser(params: ApiTypes.UpdateUserParams, body: ApiTypes.UpdateUserBody, config?: RequestConfig): Promise<ApiTypes.UpdateUserResponse> {
  return makeRequest<ApiTypes.UpdateUserResponse>({
    method: 'PUT',
    url: `/api/users/${params.id}`,
    body,
    baseURL: BASE_URL,
    ...config,
  });
}

/**
 * Update specific fields of a user
 */
export async function patchUser(params: ApiTypes.PatchUserParams, body: ApiTypes.PatchUserBody, config?: RequestConfig): Promise<ApiTypes.PatchUserResponse> {
  return makeRequest<ApiTypes.PatchUserResponse>({
    method: 'PATCH',
    url: `/api/users/${params.id}`,
    body,
    baseURL: BASE_URL,
    ...config,
  });
}

/**
 * Remove a user from the system
 */
export async function deleteUser(params: ApiTypes.DeleteUserParams, config?: RequestConfig): Promise<ApiTypes.DeleteUserResponse> {
  return makeRequest<ApiTypes.DeleteUserResponse>({
    method: 'DELETE',
    url: `/api/users/${params.id}`,
    baseURL: BASE_URL,
    ...config,
  });
}

