/**
 * Generated by react-api-weaver
 * User Management API - 1.0.0
 * REST API for managing user details with CRUD operations
 * Do not edit manually
 * 
 * This file contains all TypeScript types/interfaces for API requests and responses.
 */

export interface GetUsersParams {
  /** Maximum number of users to return */
  limit?: number;
}

export type GetUsersResponse = Record<string, any>[];

export interface CreateUserBody {
  /** User's first name */
  firstName: string;
  /** User's last name */
  lastName: string;
  /** User's gender */
  gender: 'Male' | 'Female' | 'Other';
  /** User's age in years */
  age: number;
  /** User's place of birth */
  birthPlace: string;
  /** User's country */
  country: string;
  /** List of user's hobbies */
  hobbyList?: string[];
}

export interface CreateUserResponse {
  /** Unique identifier for the user */
  id: string;
  /** User's first name */
  firstName: string;
  /** User's last name */
  lastName: string;
  /** User's gender */
  gender: 'Male' | 'Female' | 'Other';
  /** User's age in years */
  age: number;
  /** User's place of birth */
  birthPlace: string;
  /** User's country */
  country: string;
  /** List of user's hobbies */
  hobbyList: string[];
}

export interface GetUserByIdParams {
  /** User ID */
  id: string;
}

export interface GetUserByIdResponse {
  /** Unique identifier for the user */
  id: string;
  /** User's first name */
  firstName: string;
  /** User's last name */
  lastName: string;
  /** User's gender */
  gender: 'Male' | 'Female' | 'Other';
  /** User's age in years */
  age: number;
  /** User's place of birth */
  birthPlace: string;
  /** User's country */
  country: string;
  /** List of user's hobbies */
  hobbyList: string[];
}

export interface UpdateUserParams {
  /** User ID */
  id: string;
}

export interface UpdateUserBody {
  /** User's first name */
  firstName: string;
  /** User's last name */
  lastName: string;
  /** User's gender */
  gender: 'Male' | 'Female' | 'Other';
  /** User's age in years */
  age: number;
  /** User's place of birth */
  birthPlace: string;
  /** User's country */
  country: string;
  /** List of user's hobbies */
  hobbyList?: string[];
}

export interface UpdateUserResponse {
  /** Unique identifier for the user */
  id: string;
  /** User's first name */
  firstName: string;
  /** User's last name */
  lastName: string;
  /** User's gender */
  gender: 'Male' | 'Female' | 'Other';
  /** User's age in years */
  age: number;
  /** User's place of birth */
  birthPlace: string;
  /** User's country */
  country: string;
  /** List of user's hobbies */
  hobbyList: string[];
}

export interface PatchUserParams {
  /** User ID */
  id: string;
}

export interface PatchUserBody {
  /** User's first name */
  firstName?: string;
  /** User's last name */
  lastName?: string;
  /** User's gender */
  gender?: 'Male' | 'Female' | 'Other';
  /** User's age in years */
  age?: number;
  /** User's place of birth */
  birthPlace?: string;
  /** User's country */
  country?: string;
  /** List of user's hobbies */
  hobbyList?: string[];
}

export interface PatchUserResponse {
  /** Unique identifier for the user */
  id: string;
  /** User's first name */
  firstName: string;
  /** User's last name */
  lastName: string;
  /** User's gender */
  gender: 'Male' | 'Female' | 'Other';
  /** User's age in years */
  age: number;
  /** User's place of birth */
  birthPlace: string;
  /** User's country */
  country: string;
  /** List of user's hobbies */
  hobbyList: string[];
}

export interface DeleteUserParams {
  /** User ID */
  id: string;
}

export interface DeleteUserResponse {
  /** Unique identifier for the user */
  id: string;
  /** User's first name */
  firstName: string;
  /** User's last name */
  lastName: string;
  /** User's gender */
  gender: 'Male' | 'Female' | 'Other';
  /** User's age in years */
  age: number;
  /** User's place of birth */
  birthPlace: string;
  /** User's country */
  country: string;
  /** List of user's hobbies */
  hobbyList: string[];
}

