openapi: 3.0.0
info:
  title: User Management API
  description: REST API for managing user details with CRUD operations
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:3001
    description: Development server

paths:
  /api/users:
    get:
      summary: Get all users
      description: Retrieve a list of all users with optional limit parameter
      operationId: getUsers
      tags:
        - Users
      parameters:
        - name: limit
          in: query
          description: Maximum number of users to return
          required: false
          schema:
            type: integer
            minimum: 1
            example: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Create a new user
      description: Add a new user to the system
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/users/{id}:
    get:
      summary: Get user by ID
      description: Retrieve a specific user by their ID
      operationId: getUserById
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      summary: Update entire user
      description: Replace all user data with new data
      operationId: updateUser
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    patch:
      summary: Partially update user
      description: Update specific fields of a user
      operationId: patchUser
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPatch'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Delete user
      description: Remove a user from the system
      operationId: deleteUser
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - firstName
        - lastName
        - gender
        - age
        - birthPlace
        - country
        - hobbyList
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user
          example: "123e4567-e89b-12d3-a456-426614174000"
        firstName:
          type: string
          description: User's first name
          example: "John"
        lastName:
          type: string
          description: User's last name
          example: "Doe"
        gender:
          type: string
          enum:
            - Male
            - Female
            - Other
          description: User's gender
          example: "Male"
        age:
          type: integer
          minimum: 0
          description: User's age in years
          example: 28
        birthPlace:
          type: string
          description: User's place of birth
          example: "New York"
        country:
          type: string
          description: User's country
          example: "USA"
        hobbyList:
          type: array
          items:
            type: string
          description: List of user's hobbies
          example: ["Reading", "Hiking"]
    
    UserInput:
      type: object
      required:
        - firstName
        - lastName
        - gender
        - age
        - birthPlace
        - country
      properties:
        firstName:
          type: string
          description: User's first name
          example: "John"
        lastName:
          type: string
          description: User's last name
          example: "Doe"
        gender:
          type: string
          enum:
            - Male
            - Female
            - Other
          description: User's gender
          example: "Male"
        age:
          type: integer
          minimum: 0
          description: User's age in years
          example: 28
        birthPlace:
          type: string
          description: User's place of birth
          example: "New York"
        country:
          type: string
          description: User's country
          example: "USA"
        hobbyList:
          type: array
          items:
            type: string
          description: List of user's hobbies
          example: ["Reading", "Hiking"]
          default: []
    
    UserPatch:
      type: object
      properties:
        firstName:
          type: string
          description: User's first name
          example: "John"
        lastName:
          type: string
          description: User's last name
          example: "Doe"
        gender:
          type: string
          enum:
            - Male
            - Female
            - Other
          description: User's gender
          example: "Male"
        age:
          type: integer
          minimum: 0
          description: User's age in years
          example: 28
        birthPlace:
          type: string
          description: User's place of birth
          example: "New York"
        country:
          type: string
          description: User's country
          example: "USA"
        hobbyList:
          type: array
          items:
            type: string
          description: List of user's hobbies
          example: ["Reading", "Hiking"]
    
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "User not found"
